%_Películas_y_géneros

pelicula_genero('Mad_Max:_Furia_en_el_Camino','Acción').
pelicula_genero('Duro_de_Matar','Acción').
pelicula_genero('Indiana_Jones','Aventura').
pelicula_genero('El_Señor_de_los_Anillos','Aventura').
pelicula_genero('Supercool','Comedia').
pelicula_genero('Dos_Tontos_en_Fuga','Comedia').
pelicula_genero('El_Padrino','Drama').
pelicula_genero('Sueños_de_Libertad','Drama').
pelicula_genero('El_Exorcista','Terror').
pelicula_genero('Pesadilla_en_la_Calle_del_Infierno','Terror').
pelicula_genero('La_Guerra_de_las_Galaxias','Ciencia_ficción').
pelicula_genero('El_Cazador_Implacable','Ciencia_ficción').
pelicula_genero('Harry_Potter','Fantasía').

pelicula_genero('Las_Crónicas_de_Narnia','Fantasía').
pelicula_genero('La_Novicia_Rebelde','Musical').
pelicula_genero('La_La_Land','Musical').
pelicula_genero('Toy_Story','Infantil').
pelicula_genero('Shrek','Infantil').
pelicula_genero('Orgullo_y_Prejuicio','Romance').
pelicula_genero('Diario_de_una_Pasión','Romance').
pelicula_genero('Se7en','Thriller').
pelicula_genero('Perdida','Thriller').
pelicula_genero('Sherlock_Holmes','Misterio').
pelicula_genero('La_Chica_del_Dragón_Tatuado','Misterio').
pelicula_genero('Red_Social','Biográfica').
pelicula_genero('Gandhi','Biográfica').
pelicula_genero('El_Viaje_del_Emperador','Documental').


pelicula_genero('Bowling_for_Columbine','Documental').
pelicula_genero('Corazón_Valiente','Histórica').
pelicula_genero('La_Lista_de_Schindler','Histórica').
pelicula_genero('Rescatando_al_Soldado_Ryan','Guerra').
pelicula_genero('Dunkerque','Guerra').
pelicula_genero('El_Bueno,el_Malo_y_el_Feo','Western').
pelicula_genero('Los_Imperdonables','Western').
pelicula_genero('Mission:_Impossible','Espionaje').
pelicula_genero('James_Bond','Espionaje').
pelicula_genero('Stand_by_Me','Coming-of-age').
pelicula_genero('Lady_Bird','Coming-of-age').
pelicula_genero('Los_Infiltrados','Crimen').
pelicula_genero('Tiempos_Violentos','Crimen').
pelicula_genero('Rocky','Deporte').
pelicula_genero('El_Juego_de_la_Fortuna','Deporte').
pelicula_genero('Buscando_a_Nemo','Infantil').
pelicula_genero('Los_Increíbles','Infantil').
pelicula_genero('Frozen:_Una_Aventura_Congelada','Infantil').
pelicula_genero('Coco','Infantil').
pelicula_genero('Pacto_de_Sangre','Noir').
pelicula_genero('La_Ciudad_del_Pecado','Noir').
pelicula_genero('Fuego_Contra_Fuego','Policial').
pelicula_genero('Los_Ángeles_al_Desnudo','Policial').
pelicula_genero('Los_Vengadores','Superhéroes').
pelicula_genero('El_Caballero_de_la_Noche','Superhéroes').
pelicula_genero('Mujer_Bonita','Romance').
pelicula_genero('Cuando_Harry_Conoció_a_Sally','Romance').
pelicula_genero('El_Laberinto_del_Fauno','Fantasia').
pelicula_genero('La_Forma_del_Agua','Fantasia').
pelicula_genero('Los_Juegos_del_Hambre','Distopía').
pelicula_genero('Mad_Max:_Furia_en_el_Camino','Distopía').
pelicula_genero('Jurassic_Park','Ciencia_ficción').
pelicula_genero('E.T.,el_Extraterrestre','Ciencia_ficción').
pelicula_genero('Volver_al_Futuro','Ciencia_ficción').
pelicula_genero('El_Origen','Ciencia_ficción').
pelicula_genero('Matrix','Ciencia_ficción').
pelicula_genero('Avatar','Ciencia_ficción').
pelicula_genero('El_Terminator','Ciencia_ficción').
pelicula_genero('Interestelar','Ciencia_ficción').
pelicula_genero('Alien:_El_Octavo_Pasajero','Ciencia_ficción').
pelicula_genero('Guardianes_de_la_Galaxia','Ciencia_ficción').
pelicula_genero('Titanic','Romance').
pelicula_genero('Romeo_+_Julieta_de_William_Shakespeare','Romance').
pelicula_genero('Un_Paseo_para_Recordar','Romance').
pelicula_genero('Bajo_la_Misma_Estrella','Romance').
pelicula_genero('Realmente_Amor','Romance').
pelicula_genero('El_Diario_de_Bridget_Jones','Romance').
pelicula_genero('Moulin_Rouge:_Amor_en_Rojo','Romance').
pelicula_genero('Casablanca','Romance').
pelicula_genero('Un_Lugar_Llamado_Notting_Hill','Romance').
pelicula_genero('Locamente_Millonarios','Romance').
pelicula_genero('Scream:_Grita_Antes_de_Morir','Terror').
pelicula_genero('El_Conjuro','Terror').
pelicula_genero('Eso','Terror').
pelicula_genero('¡Huye!','Terror').
pelicula_genero('Hereditary:_El_Legado_del_Diablo','Terror').
pelicula_genero('El_Babadook','Terror').
pelicula_genero('El_Aro','Terror').
pelicula_genero('Un_Lugar_en_Silencio','Terror').
pelicula_genero('Actividad_Paranormal','Terror').
pelicula_genero('Halloween','Terror').
pelicula_genero('Forrest_Gump','Drama').
pelicula_genero('El_Club_de_la_Pelea','Drama').
pelicula_genero('Belleza_Americana','Drama').
pelicula_genero('Gladiador','Drama').
pelicula_genero('Milagros_Inesperados','Drama').
pelicula_genero('Mente_Indomable','Drama').
pelicula_genero('En_Busca_de_la_Felicidad','Drama').
pelicula_genero('12_Años_de_Esclavitud','Drama').
pelicula_genero('¿Quién_Quiere_Ser_Millonario?','Drama').
pelicula_genero('El_Discurso_del_Rey','Drama').
pelicula_genero('Tiburón','Suspenso').
pelicula_genero('El_Silencio_de_los_Inocentes','Suspenso').
pelicula_genero('Zodiaco','Suspenso').
pelicula_genero('Prisioneros','Suspenso').
pelicula_genero('Se7en','Suspenso').
pelicula_genero('La_Isla_Siniestra','Suspenso').
pelicula_genero('Perdida','Suspenso').
pelicula_genero('Memento','Suspenso').
pelicula_genero('El_Sexto_Sentido','Suspenso').
pelicula_genero('El_Cisne_Negro','Suspenso').
pelicula_genero('El_Rey_León','Infantil').
pelicula_genero('Buscando_a_Dory','Infantil').
pelicula_genero('El_Libro_de_la_Selva','Infantil').
pelicula_genero('Zootopia','Infantil').
pelicula_genero('Moana:_Un_Mar_de_Aventuras','Infantil').
pelicula_genero('Grandes_Héroes','Infantil').
pelicula_genero('Intensa-Mente','Infantil').
pelicula_genero('Mi_Villano_Favorito','Infantil').
pelicula_genero('Ralph,El_Demoledor','Infantil').
pelicula_genero('Cómo_Entrenar_a_tu_Dragón','Infantil').
pelicula_genero('El_Mago_de_Oz','Fantasía').
pelicula_genero('Alicia_en_el_País_de_las_Maravillas','Infantil').
pelicula_genero('El_Hobbit','Fantasía').
pelicula_genero('La_Princesa_Prometida','Fantasía').
pelicula_genero('Stardust:_El_Misterio_de_la_Estrella','Fantasía').
pelicula_genero('La_Historia_Sin_Fin','Fantasía').
pelicula_genero('Percy_Jackson_y_el_Ladrón_del_Rayo','Fantasía').
pelicula_genero('El_Cristal_Encantado','Fantasía').
pelicula_genero('Laberinto','Fantasía').
pelicula_genero('Eragon','Fantasía').
pelicula_genero('La_La_Land:_Una_Historia_de_Amor','Musical').
pelicula_genero('Chicago','Musical').
pelicula_genero('El_Gran_Showman','Musical').
pelicula_genero('Los_Miserables','Musical').
pelicula_genero('Vaselina','Musical').
pelicula_genero('Mamma_Mia!','Musical').
pelicula_genero('Hairspray','Musical').
pelicula_genero('Amor_Sin_Barreras','Musical').
pelicula_genero('Cantando_Bajo_la_Lluvia','Musical').
pelicula_genero('El_Fantasma_de_la_Ópera','Musical').
pelicula_genero('Rocky','Deporte').
pelicula_genero('Toro_Salvaje','Deporte').
pelicula_genero('El_Peleador','Deporte').
pelicula_genero('Creed:_Corazón_de_Campeón','Deporte').
pelicula_genero('Golpes_del_Destino','Deporte').
pelicula_genero('Recuerdos_de_los_Titanes','Deporte').
pelicula_genero('Juego_de_Honor','Deporte').
pelicula_genero('Campo_de_Sueños','Deporte').
pelicula_genero('Un_Equipo_Muy_Especial','Deporte').
pelicula_genero('Un_Sueño_Posible','Deporte').
pelicula_genero('El_Origen','Thriller').
pelicula_genero('El_Gran_Truco','Thriller').


%Películas_infantiles_de_animación
pelicula_infantil('Toy_Story','animación').
pelicula_infantil('El_Rey_León','animación').
pelicula_infantil('La_Sirenita','animación').
pelicula_infantil('Blancanieves_y_los_siete_enanitos','animación').
pelicula_infantil('Cenicienta','animación').
pelicula_infantil('Aladdin','animación').
pelicula_infantil('Mulán','animación').
pelicula_infantil('La_Bella_y_la_Bestia','animación').
pelicula_infantil('Bambi','animación').
pelicula_infantil('101_dálmatas','animación').
pelicula_infantil('Peter_Pan','animación').
pelicula_infantil('Dumbo','animación').
pelicula_infantil('Hércules','animación').
pelicula_infantil('Pocahontas','animación').
pelicula_infantil('Frozen','animación').
pelicula_infantil('Enredados','animación').
pelicula_infantil('Moana','animación').
pelicula_infantil('Zootopia','animación').
pelicula_infantil('Ratatouille','animación').
pelicula_infantil('Buscando_a_Nemo','animación').
pelicula_infantil('Cars','animación').
pelicula_infantil('Los_Increíbles','animación').
pelicula_infantil('Monsters,Inc.','animación').
pelicula_infantil('Up','animación').
pelicula_infantil('WALL_E','animación').
pelicula_infantil('Coco','animación').
pelicula_infantil('Valiente','animación').
pelicula_infantil('Lilo_&_Stitch','animación').
pelicula_infantil('El_libro_de_la_selva','animación').
pelicula_infantil('Alicia_en_el_país_de_las_maravillas','animación').
pelicula_infantil('Tarzán','animación').
pelicula_infantil('Los_Aristogatos','animación').
pelicula_infantil('Ralph_el_demoledor','animación').
pelicula_infantil('La_dama_y_el_vagabundo','animación').
pelicula_infantil('La_princesa_y_el_sapo','animación').
pelicula_infantil('Bolt','animación').
pelicula_infantil('Big_Hero_6','animación').
pelicula_infantil('El_jorobado_de_Notre_Dame','animación').
pelicula_infantil('Atlantis:_El_imperio_perdido','animación').
pelicula_infantil('Oliver_y_su_pandilla','animación').
pelicula_infantil('Tierra_de_osos','animación').
pelicula_infantil('El_emperador_y_sus_locuras','animación').
pelicula_infantil('Hermano_oso','animación').
pelicula_infantil('Zafarrancho_en_el_rancho','animación').
pelicula_infantil('Chicken_Little','animación').
pelicula_infantil('Río','animación').
pelicula_infantil('El_camino_hacia_El_Dorado','animación').
pelicula_infantil('Shrek','animación').
pelicula_infantil('Kung_Fu_Panda','animación').
pelicula_infantil('Madagascar','animación').
pelicula_infantil('Cómo_entrenar_a_tu_dragón','animación').

%_Películas_infantiles_live_action
pelicula_infantil('Mary_Poppins','live_action').
pelicula_infantil('Mi_pobre_angelito','live_action').
pelicula_infantil('Jumanji','live_action').
pelicula_infantil('El_jardín_secreto','live_action').
pelicula_infantil('Harry_Potter_y_la_piedra_filosofal','live_action').
pelicula_infantil('Harry_Potter_y_la_cámara_secreta','live_action').
pelicula_infantil('La_historia_sin_fin','live_action').
pelicula_infantil('Matilda','live_action').
pelicula_infantil('Stuart_Little','live_action').
pelicula_infantil('Una_noche_en_el_museo','live_action').
pelicula_infantil('Chitty_Chitty_Bang_Bang','live_action').
pelicula_infantil('Willy_Wonka_y_la_fábrica_de_chocolate','live_action').
pelicula_infantil('Los_Goonies','live_action').
pelicula_infantil('Spy_Kids','live_action').
pelicula_infantil('Hook','live_action').
pelicula_infantil('Las_crónicas_de_Narnia:_El_león,la_bruja_y_el_ropero','live_action').
pelicula_infantil('Las_crónicas_de_Narnia:_El_príncipe_Caspian','live_action').
pelicula_infantil('La_princesa_prometida','live_action').
pelicula_infantil('Paddington','live_action').
pelicula_infantil('El_regreso_de_Mary_Poppins','live_action').
pelicula_infantil('Peter_Rabbit','live_action').
pelicula_infantil('Peter_Rabbit_2:_A_la_fuga','live_action').
pelicula_infantil('La_dama_y_el_vagabundo_(2019)','live_action').
pelicula_infantil('El_Rey_León_(2019)','live_action').
pelicula_infantil('Aladdin_(2019)','live_action').
pelicula_infantil('Dumbo_(2019)','live_action').
pelicula_infantil('La_Bella_y_la_Bestia_(2017)','live_action').
pelicula_infantil('Christopher_Robin','live_action').
pelicula_infantil('El_libro_de_la_selva_(2016)','live_action').
pelicula_infantil('Maléfica','live_action').
pelicula_infantil('Maléfica:_Dueña_del_mal','live_action').
pelicula_infantil('El_Cascanueces_y_los_Cuatro_Reinos','live_action').
pelicula_infantil('Alicia_en_el_país_de_las_maravillas_(2010)','live_action').
pelicula_infantil('Alicia_a_través_del_espejo','live_action').
pelicula_infantil('Cenicienta_(2015)','live_action').
pelicula_infantil('El_dragón_de_Pete','live_action').
pelicula_infantil('Aventuras_en_la_gran_ciudad','live_action').
pelicula_infantil('La_niñera_mágica','live_action').
pelicula_infantil('Querida,encogí_a_los_niños','live_action').
pelicula_infantil('Una_serie_de_eventos_desafortunados','live_action').
pelicula_infantil('El_gato_con_sombrero','live_action').
pelicula_infantil('Las_aventuras_de_Sharkboy_y_Lavagirl','live_action').
pelicula_infantil('Dora_y_la_ciudad_perdida','live_action').
pelicula_infantil('Paddington_2','live_action').
pelicula_infantil('Mi_amigo_el_gigante','live_action').
pelicula_infantil('El_hogar_de_Miss_Peregrine_para_niños_peculiares','live_action').

%ganadoras_de_oscar
ganadora_oscar('Toy_Story',1996,'Premio_especial_innovaccion').
ganadora_oscar('El_Rey_Leon',1995,'Mejor_Banda_Original').
ganadora_oscar('El_Rey_Leon',1995,'Mejor_Canción_Original').
ganadora_oscar('Frozen',2014,'Mejor_Película_de_Animación').
ganadora_oscar('Frozen',2014,'Mejor_Canción_Original').
ganadora_oscar('Up',2010,'Mejor_Película_de_Animación').
ganadora_oscar('Up',2010,'Mejor_Banda_Sonora_Original').
ganadora_oscar('WALL_E',2009,'Mejor_Película_de_Animación').
ganadora_oscar('Coco',2018,'Mejor_Película_de_Animación').
ganadora_oscar('Coco',2018,'Mejor_Canción_Original').
ganadora_oscar('Ratatouille',2008,'Mejor_Película_de_Animación').
ganadora_oscar('Buscando_a_Nemo',2004,'Mejor_Película_de_Animación').
ganadora_oscar('Los_Increibles',2005,'Mejor_Película_de_Animación').
ganadora_oscar('Los_Increibles',2005,'Mejor_Edición_de_Sonido').
ganadora_oscar('Shrek',2002,'Mejor_Película_de_Animación').
ganadora_oscar('Mary_Poppins',1965,'Mejor_Actriz').
ganadora_oscar('Mary_Poppins',1965,'Mejor_Edición').
ganadora_oscar('Mary_Poppins',1965,'Mejores_Efectos_Visuales').
ganadora_oscar('Mary_Poppins',1965,'Mejor_Banda_Sonora_Original').
ganadora_oscar('Mary_Poppins',1965,'Mejor_Canción_Original').
ganadora_oscar('El_Jorobado_de_Notre_Dame',1939,'Mejor_Fotografía').
ganadora_oscar('El_Jorobado_de_Notre_Dame',1939,'Mejor_Música').
ganadora_oscar('El_Libro_de_la_Selva_(2016)',2017,'Mejores_Efectos_Visuales').
ganadora_oscar('El_Señor_de_los_Anillos',2002,'Mejor_Fotografía').
ganadora_oscar('El_Señor_de_los_Anillos',2002,'Mejor_Maquillaje').
ganadora_oscar('El_Señor_de_los_Anillos',2002,'Mejor_Banda_Sonora_Original').
ganadora_oscar('El_Señor_de_los_Anillos',2002,'Mejor_Efectos_Visuales').
ganadora_oscar('El_Padrino',1973,'Mejor_Película').
ganadora_oscar('El_Padrino',1973,'Mejor_Actor').
ganadora_oscar('El_Padrino',1973,'Mejor_Guión_Adaptado').
ganadora_oscar('El_Exorcista',1974,'Mejor_Guión_Adaptado').
ganadora_oscar('El_Exorcista',1974,'Mejor_Sonido').
ganadora_oscar('La_Guerra_de_las_Galaxia',1978,'Mejor_Diseño_de_Produccion').
ganadora_oscar('La_Guerra_de_las_Galaxia',1978,'Mejor_Dirección').
ganadora_oscar('La_Guerra_de_las_Galaxia',1978,'Mejor_Actor_de_Reparto').
ganadora_oscar('La_Guerra_de_las_Galaxia',1978,'Mejor_Guion_Original').
ganadora_oscar('La_Guerra_de_las_Galaxia',1978,'Mejor_Montaje').
ganadora_oscar('La_Guerra_de_las_Galaxia',1978,'Mejor_Banda_Sonora_Original').
ganadora_oscar('El_Cazador_Implacable',1979,'Mejor_Película').
ganadora_oscar('El_Cazador_Implacable',1979,'Mejor_Director').
ganadora_oscar('El_Cazador_Implacable',1979,'Mejor_Actor_de_Reparto').
ganadora_oscar('El_Cazador_Implacable',1979,'Mejor_Montaje').
ganadora_oscar('El_Cazador_Implacable',1979,'Mejor_Sonido').
/*



*/

pelicula_director(Titulo,Director).
critica_imdb(Pelicula,Calificacion).
actor_pelicula(Actor,Pelicula).
año_estreno(Pelicula,Año).
idioma_pelicula(Pelicula,Idioma).
clasificacion_pelicula(Pelicula,Clasificacion).
actor_protagonista(Pelicula,Actor).
actriz_protagonista(Pelicula,Actriz).
actor_secundario(Pelicula,Actor).
actriz_secundaria(Pelicula,Actriz).
basado_en(Pelicula,Fuente).
disponible_streaming(Pelicula,Plataforma).


