%_Películas_y_géneros

pelicula_genero('Mad_Max:_Furia_en_el_Camino','Acción').
pelicula_genero('Duro_de_Matar','Acción').
pelicula_genero('Indiana_Jones','Aventura').
pelicula_genero('El_señor_de_los_anillos:_Las_dos_torres','Aventura').
pelicula_genero('Supercool','Comedia').
pelicula_genero('Dos_Tontos_en_Fuga','Comedia').
pelicula_genero('El_Padrino','Drama').
pelicula_genero('Sueños_de_Libertad','Drama').
pelicula_genero('El_Exorcista','Terror').
pelicula_genero('Pesadilla_en_la_Calle_del_Infierno','Terror').
pelicula_genero('La_Guerra_de_las_Galaxias','Ciencia_ficción').
pelicula_genero('El_Cazador_Implacable','Ciencia_ficción').
pelicula_genero('Harry_Potter_y_la_piedra_filosofal','Fantasía').
pelicula_genero('Las_crónicas_de_Narnia:_ón,_la_bruja_y_el_ropero','Fantasía').
pelicula_genero('La_Novicia_Rebelde','Musical').
pelicula_genero('La_La_Land._Una_historia_de_amor','Musical').
pelicula_genero('Toy_Story','Infantil').
pelicula_genero('Shrek','Infantil').
pelicula_genero('Orgullo_y_Prejuicio','Romance').
pelicula_genero('Diario_de_una_Pasión','Romance').
pelicula_genero('Se7en','Thriller').
pelicula_genero('Perdida','Thriller').
pelicula_genero('Sherlock_Holmes','Misterio').
pelicula_genero('La_Chica_del_Dragón_Tatuado','Misterio').
pelicula_genero('Red_Social','Biográfica').
pelicula_genero('Gandhi','Biográfica').
pelicula_genero('El_Viaje_del_Emperador','Documental').
pelicula_genero('Bowling_for_Columbine','Documental').
pelicula_genero('Corazón_Valiente','Histórica').
pelicula_genero('La_Lista_de_Schindler','Histórica').
pelicula_genero('Rescatando_al_Soldado_Ryan','Guerra').
pelicula_genero('Dunkerque','Guerra').
pelicula_genero('El_Bueno,el_Malo_y_el_Feo','Western').
pelicula_genero('Los_Imperdonables','Western').
pelicula_genero('Mission:_Impossible','Espionaje').
pelicula_genero('James_Bond_at_the_Movies','Espionaje').
pelicula_genero('Stand_by_Me','Coming-of-age').
pelicula_genero('Lady_Bird','Coming-of-age').
pelicula_genero('Los_Infiltrados','Crimen').
pelicula_genero('Tiempos_Violentos','Crimen').

pelicula_genero('Rocky','Deporte').
pelicula_genero('El_Juego_de_la_Fortuna','Deporte').
pelicula_genero('Buscando_a_Nemo','Infantil').
pelicula_genero('Los_Increíbles','Infantil').
pelicula_genero('Frozen:_Una_Aventura_Congelada','Infantil').
pelicula_genero('Coco','Infantil').
pelicula_genero('Pacto_de_Sangre','Noir').
pelicula_genero('La_Ciudad_del_Pecado','Noir').
pelicula_genero('Fuego_Contra_Fuego','Policial').
pelicula_genero('Los_Ángeles_al_Desnudo','Policial').
pelicula_genero('The_Avengers:_Los_Vengadores','Superhéroes').
pelicula_genero('Batman:_El_caballero_de_la_noche','Superhéroes').
pelicula_genero('Mujer_Bonita','Romance').
pelicula_genero('Cuando_Harry_Conoció_a_Sally','Romance').
pelicula_genero('El_Laberinto_del_Fauno','Fantasia').

pelicula_genero('La_Forma_del_Agua','Fantasia').
pelicula_genero('Los_Juegos_del_Hambre','Distopía').
pelicula_genero('Mad_Max:_Furia_en_el_Camino','Distopía').
pelicula_genero('Jurassic_Park','Ciencia_ficción').
pelicula_genero('E.T.,el_Extraterrestre','Ciencia_ficción').
pelicula_genero('Volver_al_Futuro','Ciencia_ficción').
pelicula_genero('El_Origen','Ciencia_ficción').
pelicula_genero('Matrix','Ciencia_ficción').
pelicula_genero('Avatar','Ciencia_ficción').
pelicula_genero('Terminator','Ciencia_ficción').
pelicula_genero('Interestelar','Ciencia_ficción').
pelicula_genero('Alien:_El_Octavo_Pasajero','Ciencia_ficción').
pelicula_genero('Guardianes_de_la_Galaxia','Ciencia_ficción').
pelicula_genero('Titanic','Romance').
pelicula_genero('Romeo_+_Julieta','Romance').
pelicula_genero('Un_Paseo_para_Recordar','Romance').
pelicula_genero('Bajo_la_Misma_Estrella','Romance').
pelicula_genero('Realmente_Amor','Romance').
pelicula_genero('El_Diario_de_Bridget_Jones','Romance').
pelicula_genero('Moulin_Rouge:_Amor_en_Rojo','Romance').
pelicula_genero('Casablanca','Romance').
pelicula_genero('Un_Lugar_Llamado_Notting_Hill','Romance').
pelicula_genero('Locamente_Millonarios','Romance').
pelicula_genero('Scream:_Grita_Antes_de_Morir','Terror').
pelicula_genero('El_Conjuro','Terror').
pelicula_genero('Eso','Terror').
pelicula_genero('¡Huye!','Terror').
pelicula_genero('Hereditary:_El_Legado_del_Diablo','Terror').
pelicula_genero('El_Babadook','Terror').
pelicula_genero('El_Aro','Terror').
pelicula_genero('Un_Lugar_en_Silencio','Terror').
pelicula_genero('Actividad_Paranormal','Terror').
pelicula_genero('Halloween','Terror').
pelicula_genero('Forrest_Gump','Drama').
pelicula_genero('El_Club_de_la_Pelea','Drama').
pelicula_genero('Belleza_Americana','Drama').
pelicula_genero('Gladiador','Drama').
pelicula_genero('Milagros_Inesperados','Drama').
pelicula_genero('Mente_Indomable','Drama').
pelicula_genero('En_Busca_de_la_Felicidad','Drama').
pelicula_genero('12_Años_de_Esclavitud','Drama').
pelicula_genero('¿Quién_Quiere_Ser_Millonario?','Drama').
pelicula_genero('El_Discurso_del_Rey','Drama').
pelicula_genero('Tiburón','Suspenso').
pelicula_genero('El_Silencio_de_los_Inocentes','Suspenso').
pelicula_genero('Zodiaco','Suspenso').
pelicula_genero('Prisioneros','Suspenso').
pelicula_genero('Se7en','Suspenso').
pelicula_genero('La_Isla_Siniestra','Suspenso').
pelicula_genero('Perdida','Suspenso').
pelicula_genero('Memento','Suspenso').
pelicula_genero('El_Sexto_Sentido','Suspenso').
pelicula_genero('El_Cisne_Negro','Suspenso').
pelicula_genero('El_Rey_León','Infantil').
pelicula_genero('Buscando_a_Dory','Infantil').
pelicula_genero('El_Libro_de_la_Selva','Infantil').
pelicula_genero('Zootopia','Infantil').
pelicula_genero('Moana:_Un_Mar_de_Aventuras','Infantil').
pelicula_genero('Grandes_Héroes','Infantil').
pelicula_genero('Intensa-Mente','Infantil').
pelicula_genero('Mi_Villano_Favorito','Infantil').
pelicula_genero('Ralph,El_Demoledor','Infantil').
pelicula_genero('Cómo_Entrenar_a_tu_Dragón','Infantil').
pelicula_genero('El_Mago_de_Oz','Fantasía').
pelicula_genero('Alicia_en_el_País_de_las_Maravillas','Infantil').
pelicula_genero('El Hobbit:_Un_viaje_inesperado','Fantasía').
pelicula_genero('La_Princesa_Prometida','Fantasía').
pelicula_genero('Stardust:_El_Misterio_de_la_Estrella','Fantasía').
pelicula_genero('La_Historia_Sin_Fin','Fantasía').
pelicula_genero('Percy_Jackson_y_el_Ladrón_del_Rayo','Fantasía').
pelicula_genero('El_Cristal_Encantado','Fantasía').
pelicula_genero('Laberinto','Fantasía').
pelicula_genero('Eragon','Fantasía').
pelicula_genero('La_La_Land:_Una_Historia_de_Amor','Musical').
pelicula_genero('Chicago','Musical').
pelicula_genero('El_Gran_Showman','Musical').
pelicula_genero('Los_Miserables','Musical').
pelicula_genero('Vaselina','Musical').
pelicula_genero('Mamma_Mia!','Musical').
pelicula_genero('Hairspray','Musical').
pelicula_genero('Amor_Sin_Barreras','Musical').
pelicula_genero('Cantando_Bajo_la_Lluvia','Musical').
pelicula_genero('El_Fantasma_de_la_Ópera','Musical').
pelicula_genero('Rocky','Deporte').
pelicula_genero('Toro_Salvaje','Deporte').
pelicula_genero('El_Peleador','Deporte').
pelicula_genero('Creed:_Corazón_de_Campeón','Deporte').
pelicula_genero('Golpes_del_Destino','Deporte').
pelicula_genero('Recuerdos_de_los_Titanes','Deporte').
pelicula_genero('Juego_de_Honor','Deporte').
pelicula_genero('Campo_de_Sueños','Deporte').
pelicula_genero('Un_Equipo_Muy_Especial','Deporte').
pelicula_genero('Un_Sueño_Posible','Deporte').
pelicula_genero('El_Origen','Thriller').
pelicula_genero('El_Gran_Truco','Thriller').


%Películas_infantiles_de_animación
pelicula_infantil('Toy_Story','animación').
pelicula_infantil('El_Rey_León','animación').
pelicula_infantil('La_Sirenita','animación').
pelicula_infantil('Blancanieves_y_los_siete_enanitos','animación').
pelicula_infantil('Cenicienta','animación').
pelicula_infantil('Aladdin','animación').
pelicula_infantil('Mulán','animación').
pelicula_infantil('La_Bella_y_la_Bestia','animación').
pelicula_infantil('Bambi','animación').
pelicula_infantil('101_dálmatas','animación').
pelicula_infantil('Peter_Pan','animación').
pelicula_infantil('Dumbo','animación').
pelicula_infantil('Hércules','animación').
pelicula_infantil('Pocahontas','animación').
pelicula_infantil('Frozen:_Una_Aventura_Congelada','animación').
pelicula_infantil('Enredados','animación').
pelicula_infantil('Moana','animación').
pelicula_infantil('Zootopia','animación').
pelicula_infantil('Ratatouille','animación').
pelicula_infantil('Buscando_a_Nemo','animación').
pelicula_infantil('Cars','animación').
pelicula_infantil('Los_Increíbles','animación').
pelicula_infantil('Monsters,Inc.','animación').
pelicula_infantil('Up','animación').
pelicula_infantil('WALL_E','animación').
pelicula_infantil('Coco','animación').
pelicula_infantil('Valiente','animación').
pelicula_infantil('Lilo_&_Stitch','animación').
pelicula_infantil('El_libro_de_la_selva','animación').
pelicula_infantil('Alicia_en_el_país_de_las_maravillas','animación').
pelicula_infantil('Tarzán','animación').
pelicula_infantil('Los_Aristogatos','animación').
pelicula_infantil('Ralph_el_demoledor','animación').
pelicula_infantil('La_dama_y_el_vagabundo','animación').
pelicula_infantil('La_princesa_y_el_sapo','animación').
pelicula_infantil('Bolt','animación').
pelicula_infantil('Big_Hero_6','animación').
pelicula_infantil('El_jorobado_de_Notre_Dame','animación').
pelicula_infantil('Atlantis:_El_imperio_perdido','animación').
pelicula_infantil('Oliver_y_su_pandilla','animación').
pelicula_infantil('Tierra_de_osos','animación').
pelicula_infantil('El_emperador_y_sus_locuras','animación').
pelicula_infantil('Hermano_oso','animación').
pelicula_infantil('Zafarrancho_en_el_rancho','animación').
pelicula_infantil('Chicken_Little','animación').
pelicula_infantil('Río','animación').
pelicula_infantil('El_camino_hacia_El_Dorado','animación').
pelicula_infantil('Shrek','animación').
pelicula_infantil('Kung_Fu_Panda','animación').
pelicula_infantil('Madagascar','animación').
pelicula_infantil('Cómo_entrenar_a_tu_dragón','animación').

%_Películas_infantiles_live_action
pelicula_infantil('Mary_Poppins','live_action').
pelicula_infantil('Mi_pobre_angelito','live_action').
pelicula_infantil('Jumanji','live_action').
pelicula_infantil('El_jardín_secreto','live_action').
pelicula_infantil('Harry_Potter_y_la_piedra_filosofal','live_action').
pelicula_infantil('Harry_Potter_y_la_cámara_secreta','live_action').
pelicula_infantil('La_historia_sin_fin','live_action').
pelicula_infantil('Matilda','live_action').
pelicula_infantil('Stuart_Little','live_action').
pelicula_infantil('Una_noche_en_el_museo','live_action').
pelicula_infantil('Chitty_Chitty_Bang_Bang','live_action').
pelicula_infantil('Willy_Wonka_y_la_fábrica_de_chocolate','live_action').
pelicula_infantil('Los_Goonies','live_action').
pelicula_infantil('Spy_Kids','live_action').
pelicula_infantil('Hook','live_action').
pelicula_infantil('Las_crónicas_de_Narnia:_El_león,la_bruja_y_el_ropero','live_action').
pelicula_infantil('Las_crónicas_de_Narnia:_El_príncipe_Caspian','live_action').
pelicula_infantil('La_princesa_prometida','live_action').
pelicula_infantil('Paddington','live_action').
pelicula_infantil('El_regreso_de_Mary_Poppins','live_action').
pelicula_infantil('Peter_Rabbit','live_action').
pelicula_infantil('Peter_Rabbit_2:_A_la_fuga','live_action').
pelicula_infantil('La_dama_y_el_vagabundo_(2019)','live_action').
pelicula_infantil('El_Rey_León_(2019)','live_action').
pelicula_infantil('Aladdin_(2019)','live_action').
pelicula_infantil('Dumbo_(2019)','live_action').
pelicula_infantil('La_Bella_y_la_Bestia_(2017)','live_action').
pelicula_infantil('Christopher_Robin','live_action').
pelicula_infantil('El_libro_de_la_selva_(2016)','live_action').
pelicula_infantil('Maléfica','live_action').
pelicula_infantil('Maléfica:_Dueña_del_mal','live_action').
pelicula_infantil('El_Cascanueces_y_los_Cuatro_Reinos','live_action').
pelicula_infantil('Alicia_en_el_país_de_las_maravillas_(2010)','live_action').
pelicula_infantil('Alicia_a_través_del_espejo','live_action').
pelicula_infantil('Cenicienta_(2015)','live_action').
pelicula_infantil('El_dragón_de_Pete','live_action').
pelicula_infantil('Aventuras_en_la_gran_ciudad','live_action').
pelicula_infantil('La_niñera_mágica','live_action').
pelicula_infantil('Querida,encogí_a_los_niños','live_action').
pelicula_infantil('Una_serie_de_eventos_desafortunados','live_action').
pelicula_infantil('El_gato_con_sombrero','live_action').
pelicula_infantil('Las_aventuras_de_Sharkboy_y_Lavagirl','live_action').
pelicula_infantil('Dora_y_la_ciudad_perdida','live_action').
pelicula_infantil('Paddington_2','live_action').
pelicula_infantil('Mi_amigo_el_gigante','live_action').
pelicula_infantil('El_hogar_de_Miss_Peregrine_para_niños_peculiares','live_action').

%ganadoras de oscar
gano_oscar_en('Toy_Story',1996,'Premio_especial_innovaccion').
gano_oscar_en('Toy_Story',1996,'Mejor_Guion_Original').
gano_oscar_en('El_Rey_Leon',1995,'Mejor_Banda_Original').
gano_oscar_en('El_Rey_Leon',1995,'Mejor_Canción_Original').
gano_oscar_en('Frozen:_Una_Aventura_Congelada',2014,'Mejor_Película_de_Animación').
gano_oscar_en('Frozen:_Una_Aventura_Congelada',2014,'Mejor_Canción_Original').
gano_oscar_en('Up',2010,'Mejor_Película_de_Animación').
gano_oscar_en('Up',2010,'Mejor_Banda_Sonora_Original').
gano_oscar_en('WALL_E',2009,'Mejor_Película_de_Animación').
gano_oscar_en('Coco',2018,'Mejor_Película_de_Animación').
gano_oscar_en('Coco',2018,'Mejor_Canción_Original').
gano_oscar_en('Ratatouille',2008,'Mejor_Película_de_Animación').
gano_oscar_en('Buscando_a_Nemo',2004,'Mejor_Película_de_Animación').
gano_oscar_en('Los_Increibles',2005,'Mejor_Película_de_Animación').
gano_oscar_en('Los_Increibles',2005,'Mejor_Edición_de_Sonido').
gano_oscar_en('Shrek',2002,'Mejor_Película_de_Animación').
gano_oscar_en('Mary_Poppins',1965,'Mejor_Actriz').
gano_oscar_en('Mary_Poppins',1965,'Mejor_Edición').
gano_oscar_en('Mary_Poppins',1965,'Mejores_Efectos_Visuales').
gano_oscar_en('Mary_Poppins',1965,'Mejor_Banda_Sonora_Original').
gano_oscar_en('Mary_Poppins',1965,'Mejor_Canción_Original').
gano_oscar_en('El_Jorobado_de_Notre_Dame',1939,'Mejor_Fotografía').
gano_oscar_en('El_Jorobado_de_Notre_Dame',1939,'Mejor_Música').
gano_oscar_en('El_Libro_de_la_Selva_(2016)',2017,'Mejores_Efectos_Visuales').
gano_oscar_en('El_señor_de_los_anillos:_Las_dos_torres',2002,'Mejor_Fotografía').
gano_oscar_en('El_señor_de_los_anillos:_Las_dos_torres',2002,'Mejor_Maquillaje').
gano_oscar_en('El_señor_de_los_anillos:_Las_dos_torres',2002,'Mejor_Banda_Sonora_Original').
gano_oscar_en('El_señor_de_los_anillos:_Las_dos_torres',2002,'Mejor_Efectos_Visuales').
gano_oscar_en('El_Padrino',1973,'Mejor_Película').
gano_oscar_en('El_Padrino',1973,'Mejor_Actor').
gano_oscar_en('El_Padrino',1973,'Mejor_Guión_Adaptado').
gano_oscar_en('El_Exorcista',1974,'Mejor_Guión_Adaptado').
gano_oscar_en('El_Exorcista',1974,'Mejor_Sonido').
gano_oscar_en('La_Guerra_de_las_Galaxia',1978,'Mejor_Diseño_de_Produccion').
gano_oscar_en('La_Guerra_de_las_Galaxia',1978,'Mejor_Dirección').
gano_oscar_en('La_Guerra_de_las_Galaxia',1978,'Mejor_Actor_de_Reparto').
gano_oscar_en('La_Guerra_de_las_Galaxia',1978,'Mejor_Guion_Original').
gano_oscar_en('La_Guerra_de_las_Galaxia',1978,'Mejor_Montaje').
gano_oscar_en('La_Guerra_de_las_Galaxia',1978,'Mejor_Banda_Sonora_Original').
gano_oscar_en('El_Cazador_Implacable',1979,'Mejor_Película').
gano_oscar_en('El_Cazador_Implacable',1979,'Mejor_Director').
gano_oscar_en('El_Cazador_Implacable',1979,'Mejor_Actor_de_Reparto').
gano_oscar_en('El_Cazador_Implacable',1979,'Mejor_Montaje').
gano_oscar_en('El_Cazador_Implacable',1979,'Mejor_Sonido').
gano_oscar_en('Las_crónicas_de_Narnia:_ón,_la_bruja_y_el_ropero',2006,'Mejor_Maquillaje_y_Peluquería').
gano_oscar_en('La_Novicia_Rebelde',1966,'Mejor_Película').
gano_oscar_en('La_Novicia_Rebelde',1966,'Mejor_Director').
gano_oscar_en('La_Novicia_Rebelde',1966,'Mejor_Edición').
gano_oscar_en('La_Novicia_Rebelde',1966,'Mejor_Sonido').
gano_oscar_en('La_Novicia_Rebelde',1966,'Mejor_Canción_Original').
gano_oscar_en('La_La_Land._Una_historia_de_amor',2017,'Mejor_Director').
gano_oscar_en('La_La_Land._Una_historia_de_amor',2017,'Mejor_Actriz').
gano_oscar_en('La_La_Land._Una_historia_de_amor',2017,'Mejor_Banda_Sonora_Original').
gano_oscar_en('La_La_Land._Una_historia_de_amor',2017,'Mejor_Canción_Original').
gano_oscar_en('La_La_Land._Una_historia_de_amor',2017,'Mejor_Diseño_de_Produccion').
gano_oscar_en('Orgullo_y_Prejuicio',2006,'Mejor_Actriz').
gano_oscar_en('Orgullo_y_Prejuicio',2006,'Mejor_Banda_Sonora_Original').
gano_oscar_en('La_Chica_del_Dragón_Tatuado',2012,'Mejor_Montaje').
gano_oscar_en('Red_Social',2011,'Mejor_Guión_Adaptado').
gano_oscar_en('Red_Social',2011,'Mejor_Banda_Sonora_Original').
gano_oscar_en('Red_Social',2011,'Mejor_Montaje').
gano_oscar_en('Gandhi',1983,'Mejor_Película').
gano_oscar_en('Gandhi',1983,'Mejor_Actor_de_Reparto').
gano_oscar_en('Gandhi',1983,'Mejor_Director').
gano_oscar_en('Gandhi',1983,'Mejor_Guion_Original').
gano_oscar_en('Gandhi',1983,'Mejor_Guion_Original').
gano_oscar_en('Gandhi',1983,'Mejor_Fotografía').
gano_oscar_en('El_Viaje_del_Emperador',2006,'Mejor_Documental').
gano_oscar_en('Bowling_for_Columbine',2003,'Mejor_Documental').
gano_oscar_en('Corazón_Valiente',1996,'Mejor_Película').
gano_oscar_en('Corazón_Valiente',1996,'Mejor_Director').
gano_oscar_en('Corazón_Valiente',1996,'Mejor_Fotografía').
gano_oscar_en('La_Lista_de_Schindler',1994,'Mejor_Película').
gano_oscar_en('La_Lista_de_Schindler',1994,'Mejor_Guion_Original').
gano_oscar_en('Rescatando_al_Soldado_Ryan',1999,'Mejor_Director').
gano_oscar_en('Rescatando_al_Soldado_Ryan',1999,'Mejor_Fotografía').
gano_oscar_en('Dunkerque',2018,'Mejor_Banda_Sonora_Original').
gano_oscar_en('Los_Imperdonables',1993,'Mejor_Actriz_de_Reparto').
gano_oscar_en('Los_Imperdonables',1993,'Mejor_Director').
gano_oscar_en('Los_Infiltrados',2007,'Mejor_Película').
gano_oscar_en('Los_Infiltrados',2007,'Mejor_Guión_Adaptado').
gano_oscar_en('Tiempos_Violentos',2007,'Mejor_Guion_Original').
gano_oscar_en('Rocky',1977,'Mejor_Director').
gano_oscar_en('Rocky',1977,'Mejor_Película').
gano_oscar_en('Rocky',1977,'Mejor_Montaje').
ganadora_oscar('Los_Ángeles_al_Desnudo',1998,'Mejor_Actriz').
ganadora_oscar('Los_Ángeles_al_Desnudo',1998,'Mejor_Guión_Adaptado').



%critica_imdb
critica_imdb('Mad_Max:_Furia_en_el_Camino',8.1).
critica_imdb('Duro_de_Matar',8.2).
critica_imdb('Indiana_Jones',7.5).
critica_imdb('El_señor_de_los_anillos:_Las_dos_torres',8.8).
critica_imdb('Supercool'),7.6.
critica_imdb('Dos_Tontos_en_Fuga',6.5).
critica_imdb('El_Padrino',9.2).
critica_imdb('Sueños_de_Libertad',8.4).
critica_imdb('El_Exorcista',8.1,8.3).
critica_imdb('Pesadilla_en_la_Ca,7.9lle_del_Infierno',7.4).
critica_imdb('La_Guerra_de_las_Galaxias',8.6).
critica_imdb('El_Cazador_Implacable',8.1).
critica_imdb('Harry_Potter_y_la_piedra_filosofal',7.6).
critica_imdb('Las_crónicas_de_Narnia:_ón,_la_bruja_y_el_ropero',6.9).
critica_imdb('La_Novicia_Rebelde',8.1).
critica_imdb('La_La_Land._Una_historia_de_amor',8.0).
critica_imdb('Toy_Story',8.3).
critica_imdb('Shrek',7.9).
critica_imdb('Orgullo_y_Prejuicio',7.8).
critica_imdb('Diario_de_una_Pasión'),7.8.
critica_imdb('Se7en',8.6).
critica_imdb('Perdida',8.1).
critica_imdb('Sherlock_Holmes',7.6).
critica_imdb('La_Chica_del_Dragón_Tatuado',7.8).
critica_imdb('Red_Social',7.8).
critica_imdb('Gandhi',8.0).
critica_imdb('El_Viaje_del_Emperador',7.5).
critica_imdb('Bowling_for_Columbine',8.0).
critica_imdb('Corazón_Valiente',8.3).
critica_imdb('La_Lista_de_Schindler',9.0).
critica_imdb('Rescatando_al_Soldado_Ryan',8.6).
critica_imdb('Dunkerque',7.8).
critica_imdb('El_Bueno,el_Malo_y_el_Feo',8.8).
critica_imdb('Los_Imperdonables',8.2).
critica_imdb('Mission:_Impossible',7.2).
critica_imdb('James_Bond_at_the_Movies',7.6).
critica_imdb('Stand_by_Me',8.1).
critica_imdb('Lady_Bird',7.4).
critica_imdb('Los_Infiltrados',8.5).
critica_imdb('Tiempos_Violentos',8.9).
critica_imdb('Rocky',8.1).
critica_imdb('El_Juego_de_la_Fortuna',7.6).
critica_imdb('Buscando_a_Nemo',8.2).
critica_imdb('Los_Increíbles',8.0).
critica_imdb('Frozen:_Una_Aventura_Congelada',7.4).
critica_imdb('Coco',8.4).
critica_imdb('Pacto_de_Sangre',8.3).
critica_imdb('La_Ciudad_del_Pecado',8.0).
critica_imdb('Fuego_Contra_Fuego',8.3).
critica_imdb('Los_Ángeles_al_Desnudo',8.2).
critica_imdb('The_Avengers:_Los_Vengadores',8.0).
critica_imdb('Batman:_El_caballero_de_la_noche',9.0).
critica_imdb('Mujer_Bonita',7.1).
critica_imdb('Cuando_Harry_Conoció_a_Sally',7.7).
critica_imdb('El_Laberinto_del_Fauno',8.2).
critica_imdb('La_Forma_del_Agua',7.3).
critica_imdb('Los_Juegos_del_Hambre',7.2).
critica_imdb('Mad_Max:_Furia_en_el_Camino',8.1).
critica_imdb('Jurassic_Park',8.2).
critica_imdb('E.T.,el_Extraterrestre',7.9).
critica_imdb('Volver_al_Futuro',8.5).
critica_imdb('El_Origen',8.8).
critica_imdb('Matrix',8.7).
critica_imdb('Avatar',7.9).
critica_imdb('Terminator',8.1).
critica_imdb('Interestelar',8.7).
critica_imdb('Alien:_El_Octavo_Pasajero',8.5).
critica_imdb('Guardianes_de_la_Galaxia',8.0).
critica_imdb('Titanic',7.9).
critica_imdb('Romeo_+_Julieta',6.7).
critica_imdb('Un_Paseo_para_Recordar',7.3).
critica_imdb('Bajo_la_Misma_Estrella',7.7).
critica_imdb('Realmente_Amor',7.6).
critica_imdb('El_Diario_de_Bridget_Jones',6.8).
critica_imdb('Moulin_Rouge:_Amor_en_Rojo',7.6).
critica_imdb('Casablanca',8.5).
critica_imdb('Un_Lugar_Llamado_Notting_Hill',7.2).
critica_imdb('Locamente_Millonarios',6.9).
critica_imdb('Scream:_Grita_Antes_de_Morir',7.4).
critica_imdb('El_Conjuro',7.5).
critica_imdb('Eso',6.8).
critica_imdb('¡Huye!',7.8).
critica_imdb('Hereditary:_El_Legado_del_Diablo',7.3).
critica_imdb('El_Babadook',6.8).
critica_imdb('El_Aro'7.1).
critica_imdb('Un_Lugar_en_Silencio',7.5).
critica_imdb('Actividad_Paranormal',6.3).
critica_imdb('Halloween',7.7).
critica_imdb('Forrest_Gump',8.8).
critica_imdb('El_Club_de_la_Pelea',8.8).
critica_imdb('Belleza_Americana'8.3).  // si tiene oscar (5)
critica_imdb('Gladiador',8.5).      // si tiene oscar (5)
critica_imdb('Milagros_Inesperados',8.6).   //
critica_imdb('Mente_Indomable',8.3).  // tiene 2 oscar
critica_imdb('En_Busca_de_la_Felicidad',8.0).
critica_imdb('12_Años_de_Esclavitud',8.1).  // gano 3 oscar 
critica_imdb('¿Quién_Quiere_Ser_Millonario?',8.0). // gano 8 oscar
critica_imdb('El_Discurso_del_Rey',8.0). // gano 4 oscar
critica_imdb('Tiburón',8.1).    // gano 3 oscar
critica_imdb('El_Silencio_de_los_Inocentes',8.6). // gano 5 oscar
critica_imdb('Zodiaco',7.7).
critica_imdb('Prisioneros',8.2).
critica_imdb('Se7en',8.6).
critica_imdb('La_Isla_Siniestra',8.2).
critica_imdb('Perdida',8.1).
critica_imdb('Memento',8.4).
critica_imdb('El_Sexto_Sentido',8.2).
critica_imdb('El_Cisne_Negro',8.0). // gano 1 oscar
critica_imdb('El_Rey_León',8.5). // gano 2 oscar
critica_imdb('Buscando_a_Dory',7.2).
critica_imdb('El_Libro_de_la_Selva',7.4). // gano 1 osacar
critica_imdb('Zootopia',8.0). // gano 1 oscar
critica_imdb('Moana:_Un_Mar_de_Aventuras',7.6).
critica_imdb('Grandes_Héroes',7.8). // gano 1 osacar
critica_imdb('Intensa-Mente',8.1). // gano un oscar
critica_imdb('Mi_Villano_Favorito',7.6).
critica_imdb('Ralph,El_Demoledor',7.7).
critica_imdb('Cómo_Entrenar_a_tu_Dragón',8.1).
critica_imdb('El_Mago_de_Oz',8.1). // gano 2 oscar
critica_imdb('Alicia_en_el_País_de_las_Maravillas',6.4). // gano 2 oscar
critica_imdb('El Hobbit:_Un_viaje_inesperado',7.8).
critica_imdb('La_Princesa_Prometida',8.0).
critica_imdb('Stardust:_El_Misterio_de_la_Estrella',7.6).
critica_imdb('La_Historia_Sin_Fin',7.3).
critica_imdb('Percy_Jackson_y_el_Ladrón_del_Rayo',5.9).
critica_imdb('El_Cristal_Encantado',7.1).
critica_imdb('Laberinto',7.3).
critica_imdb('Eragon',5.1).
critica_imdb('La_La_Land:_Una_Historia_de_Amor',8.0). // gano 6 oscar
critica_imdb('Chicago',7.6). // gano 6 oscar    
critica_imdb('El_Gran_Showman',7.5).
critica_imdb('Los_Miserables'.7.5). // gano 3 oscar
critica_imdb('Vaselina',7.2).
critica_imdb('Mamma_Mia!',6.5).
critica_imdb('Hairspray',6.7).
critica_imdb('Amor_Sin_Barreras',7.1). // gano  1 oscar
critica_imdb('Cantando_Bajo_la_Lluvia',8.3).
critica_imdb('El_Fantasma_de_la_Ópera',7.2).
critica_imdb('Rocky',8.1). // gano 3 oscae
critica_imdb('Toro_Salvaje'8.1). // gano 2 oscar
critica_imdb('El_Peleador',7.8). gano 2 oscar
critica_imdb('Creed:_Corazón_de_Campeón',7.6).
critica_imdb('Golpes_del_Destino').
critica_imdb('Recuerdos_de_los_Titanes',8.1). // gano 4 oscar
critica_imdb('Juego_de_Honor',7.3).
critica_imdb('Campo_de_Sueños'7.5).
critica_imdb('Un_Equipo_Muy_Especial',7.3).
critica_imdb('Un_Sueño_Posible'7.6). //gano 1 oscar
critica_imdb('El_Origen',8.8). // gano 4 oscar
critica_imdb('El_Gran_Truco',8.5).


pelicula_director(Titulo,Director).
año_estreno(Pelicula,Año).
idioma_pelicula(Pelicula,Idioma).
clasificacion_pelicula(Pelicula,Clasificacion).
actor_protagonista(Pelicula,Actor).
actriz_protagonista(Pelicula,Actriz).
actor_secundario(Pelicula,Actor).
actriz_secundaria(Pelicula,Actriz).
basado_en(Pelicula,Fuente).
disponible_streaming(Pelicula,Plataforma).



%videojuegos
%es_videojuego(Nombre_juego).

mas_esperados('Blue_Protocol').
mas_esperados('Star_Citizen').
mas_esperados('Hollow_Knight:_Silksong').
mas_esperados('Beyond_Good_&_Evil_2').
mas_esperados('Lost_Soul_Aside').
mas_esperados('Grand_Theft_Auto_VI').
mas_esperados('The_Elder_Scrolls_VI').
mas_esperados('STALKER_2').
mas_esperados('Bus_Controller_Simulator').
mas_esperados('Black_Myth:_Wukong').
mas_esperados('The_Last_Night').
mas_esperados('Vampire:_The_Masquerade_-_Bloodlines').
mas_esperados('Little_Devil_Inside').
mas_esperados('Ashes_of_Creation').
mas_esperados('Dragon_Age:_Dreadwolf').
mas_esperados('The_Lighthouse_-_VR_Escape').
mas_esperados('Truck_Parking_Simulator').
mas_esperados('Indiana_Jones_and_the_Great_Circle').
mas_esperados('Silent_Hill_2_Remake').
mas_esperados('Fable').
mas_esperados('Mass_Effect_5').
mas_esperados('Avowed').
mas_esperados('Routine').
mas_esperados('Tale_of_Ronin').
mas_esperados('Paralives').
mas_esperados('Chrono_Odyssey').
mas_esperados('Star_Wars_Eclipse').
mas_esperados('Ambulance_Simulator').
mas_esperados('Negative_Atmosphere').
mas_esperados('Hellblade_2').
mas_esperados('Zenless_Zone_Zero').
mas_esperados('Farm_Folks').
mas_esperados('Escape_Room_Simulator').
mas_esperados('SimBus').
mas_esperados('Where_Winds_Meet').
mas_esperados('Kingdom_Come:_Deliverance_II').
mas_esperados('Metal_Slug_Tactics').
mas_esperados('Everwild').
mas_esperados('Assassins_Creed_Infinity').
mas_esperados('Judas').
mas_esperados('Godus').
mas_esperados('Gothic_Remake').
mas_esperados('Gestalt:_Steam_&_Cinder').
mas_esperados('Replaced').
mas_esperados('System_Shock_3').
mas_esperados('Path_of_Exile_2').
mas_esperados('Silent_Hill_F').
mas_esperados('Star_Wars_Outlaws').
mas_esperados('3_Minutes_to_Midnight').
mas_esperados('Crimson_Desert').
mas_esperados('The_Witcher_4').
mas_esperados('Everywhere').
mas_esperados('The_Wolf_Among_Us_2').
mas_esperados('Dragon_Ball:_Sparking!_Zero').
mas_esperados('Damnview:_Built_From_Nothing').
mas_esperados('Bushiden').
mas_esperados('Crowsworn').
mas_esperados('Silent_Hill_Townfall').
mas_esperados('Unrecord').